name = "kinh-mat-tuan-ha"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "kinh-mat-db"
database_id = "fb903c1a-51b2-466f-8c09-355598194777"

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"
